### ISSUE TITLE
Add React Router Page Structure

### ISSUE THREAD

**Issue by MatthewBozin** [Caleb-Cohen/Together#56] opened 2022-11-14 17:57 UTC
This is an issue representing task 4 of issue #29 

Add a React Router for routing between/adding new pages so that other collaborators would be able to add new pages with minimal setup.

- Add React Router and create a router in App.js that can route between pages.
- Create two dummy pages that can route between each other to demonstrate that it works and provide an example to contributors that want to create pages.
- Create a guide that shows other collaborators how to create new pages and get those pages set up with the Router. Post it as markdown in the comments of this issue.

**Comment by Caleb-Cohen** [comment] 2022-11-14 18:01
Added to project board. Can you clarify a bit? I don't think I understand what this is doing.

**Comment by MatthewBozin** [comment] 2022-11-14 18:10
I've expanded this a bit for clarity. Do you have any questions in particular?

**Comment by Caleb-Cohen** [comment] 2022-11-15 00:03
Clarification helped with the first two, thanks for the link. Is Number 3 a guide to show people how to make new pages?

**Comment by MatthewBozin** [comment] 2022-11-15 01:44
Re: number 3: Yes exactly! I'll rephrase the issue so it's more clear.

**Comment by WinstonHall** [comment] 2022-11-15 23:46
Deprecated / No longer relevant.

**Comment by MatthewBozin** [comment] 2022-11-16 00:30
@WinstonHall how is this deprecated?

**Comment by WinstonHall** [comment] 2022-11-16 00:35
We wont be using react-router, at least not what next gives us. unless they use react router dom under the hood. I hastily misread React Router for ReactRouterDom, and the third bullet point In the original post thats gonna be outline for us by design.

So maybe I should have said something like, could be updated at some point to fit our direction now.

**Comment by Caleb-Cohen** [comment] 2022-11-16 14:32
@WinstonHall There has not been a decision on Next yet. Can you post your Next template into [discussions](https://github.com/Caleb-Cohen/Together/discussions)?

**Comment by WinstonHall** [comment] 2022-11-16 15:03
@Caleb-Cohen  
      First question, the answer is do you want me to do it, if so I can start getting ready for that now while I coffee up.

      Second question, I wasn't sure if we was going to be waiting for a definitive decision on Next or not. 
            Soooooo with that in mind if I'm gonna mess with Next I would like to be sure this time. I thought we came to some 
            kind of agreement , I forget who all was there but I really didn't know the implication of how many people where 
            actually considered actively involved. 

      I just need to have a green light, I'm gun shy now  after that assumption I made yesterday lol.

**Comment by WinstonHall** [comment] 2022-11-16 21:30
Commenting to elevate that this is stalled mostly due to not being sure if we are going to use a font & back end separated strategy or Next. Honestly I'm good getting around still to at least see the states work and all the components that dont live in auth territory.

**Comment by Caleb-Cohen** [comment] 2022-11-16 22:38
> Commenting to elevate that this is stalled mostly due to not being sure if we are going to use a font & back end separated strategy or Next. Honestly I'm good getting around still to at least see the states work and all the components that dont live in auth territory.

I think this will be a good discussion for Thursday, but you are right it is stalled because we have yet to make a decision on the direction.

**Comment by Caleb-Cohen** [comment] 2022-11-16 22:47
@WinstonHall can I assign you to see if we can make react router work for this? Let's talk on Thursday and see your thoughts.

**Comment by WinstonHall** [comment] 2022-11-17 00:15
In that environment, though my brain is fried I almost feel confident that it won't work or it will do even better and shit the bed because of how we have to wrap the react.

**Comment by WinstonHall** [comment] 2022-11-21 18:56
Has this topic changed any? Can we assume it can be written in a front-end way, or have we decided if this will be a server side rendered thing?

**Comment by WinstonHall** [comment] 2022-11-21 19:03
If we deploy the front and back separately then I would suggest react-router-dom. I haven't had the time or need to learn their current version v6 https://reactrouter.com/en/main, but I'm familiar with their previous version v5 https://v5.reactrouter.com/web/guides/quick-start.

 They have a node solution in in the more current version, but I'm not use to doing routing in the back-end outside of using Next.JS.

**Comment by Caleb-Cohen** [comment] 2022-11-30 03:07
@MatthewBozin @WinstonHall closing this issue due to no longer needed.

**Closed by Caleb-Cohen** 2022-11-30 03:07 UTC
Labels: Backend
