### ISSUE TITLE
Cleanup/remove BOB templates 

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#44] opened 2022-11-12 14:23 UTC
This issue is part of the ongoing Quality of Life updates #29.

# Task
* Remove views folder which contains all the EJS files.
* Remove public folder which contains BuB favicons and other assets.

**Comment by JoeDravarol** [comment] 2022-11-12 14:37
@Caleb-Cohen I've added the third task `Remove the BOB favicon, and remove mention of BUB and 100 Devs social network.` as it was in the README MVP. Hope that is okay? 

Also, just for clarification, are we removing everything that was part of the `BUB template and 100 Devs social network` for the third task: `Remove the BOB favicon, and remove mention of BUB and 100 Devs social network.` If that is the case I can remove the second task as it would be redudant.

**Comment by JoeDravarol** [comment] 2022-11-12 14:48
Removing the third task, to keep this issue simple and easy for new contributor to work on.

**Comment by Caleb-Cohen** [comment] 2022-11-12 15:14
> @Caleb-Cohen I've added the third task `Remove the BOB favicon, and remove mention of BUB and 100 Devs social network.` as it was in the README MVP. Hope that is okay?
> 
> Also, just for clarification, are we removing everything that was part of the `BUB template and 100 Devs social network` for the third task: `Remove the BOB favicon, and remove mention of BUB and 100 Devs social network.` If that is the case I can remove the second task as it would be redudant.

They can be separate tasks.

**Comment by Caleb-Cohen** [comment] 2022-11-12 16:05
Number 1 is attempting to be addressed in #45

**Comment by code2244** [comment] 2022-11-12 19:56
Hi everyone, if the issue is not taken, I will like to do this one.

**Comment by Caleb-Cohen** [comment] 2022-11-12 21:40
@code2244 hold off just a bit we have #46 that's addressing some of these issues that we are working through and don't want you to double work on something that's already been done.

**Comment by JoeDravarol** [comment] 2022-11-12 21:53
> @code2244 hold off just a bit we have #46 that's addressing some of these issues that we are working through and don't want you to double work on something that's already been done.

I took a look at #46 everything related to EJS has not been removed yet. This issue/tasks still stands and can be contribute to. Though it is better to hold off on this issue like you said until we have merge the outstanding PRs to prevent conflicting issues.

**Comment by Caleb-Cohen** [comment] 2022-11-16 14:21
@code2244 The task removing EJS and views folder is now open.

**Comment by Caleb-Cohen** [comment] 2022-11-16 22:28
> I have the EJS folder removed with a couple handfuls of tiny fix's each in their own commit grouped together so you should be able to make a temp clone of the main then stick those updates in to that clone before so we can make sure it does what it should do.

Depending on the edits I don't see a need to make a clone of main. I can make one for you to PR to if you would really like it. Please try to ensure that the PRs are solving one issue at a time. If you've completed the Views removal please PR it.

**Closed** 2022-11-18 16:54 UTC
Labels: help wanted, Good 100Devs FI
